language: python
dist: xenial
cache: pip

stages:
  - lint
  - test

jobs:
  include:
    - python: 2.7.16
    - python: 3.5.7
    - python: 3.6.8
    - python: 3.7.3
      sudo: true

    - stage: lint
      python: 3.7
      before_install: skip
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
      after_success: skip

before_install:
  - sudo apt-get update -q
  - sudo apt-get install --no-install-recommends -y xvfb python3-dev python3-gi python3-gi-cairo
    gir1.2-gtk-3.0 libgirepository1.0-dev libcairo2-dev
install:
  - pip install poetry==1.0.0b3
  - poetry install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - xvfb-run pytest -q
after_script:
  - coverage xml
  - ./cc-test-reporter after-build --coverage-input-type coverage.py --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1e0a1432c48a12660160
    on_success: change
    on_failure: always
    on_start: never
